---
title: "Data Cleanign Process - All"
author: "Kaylin Slattery"
date: "2024-03-04"
output: html_document
---

## <span style= "color:#0C2340" > DATA IMPORTATION & SET UP <span style= "color:#0C2340" >

```{r packages, warnings=FALSE, error=FALSE, message=FALSE}
library(tidyverse)
library(DescTools)
library(janitor)
library(ggplot2)
library(jpeg)
library(chron)
library(lubridate)
library(anytime)
library(ggpubr)
library(devtools) 
#install_github("AppliedDataSciencePartners/xgboostExplainer")
library(xgboost) # Load XGBoost
library(caret) # Load Caret
library(xgboostExplainer) # Load XGboost Explainer
library(pROC) # Load proc
library(SHAPforxgboost) # Load shap for XGBoost
library(plyr)
library(Metrics)

# FOR WEB SCRAPING
library(httr) 
library(rvest) 
library(polite) 
library(jsonlite) 
```

```{r nd colors}
# setting ND colors 
nd_navy <- "#0C2340"
nd_green <- "#00843D"
nd_gold <- "#C99700"
```

```{r creating functions}
calc_num_zeros_by_col <- function(df_title) {
  cols_vec <- colnames(df_title)
  zeros_count_vec <- rep("", length=length(cols_vec))
  zeros_test_vec <- rep("", length=length(cols_vec))

  for (i in 1:length(cols_vec)){
    zeros_count_vec[i] <- sum(df_title[,i] == 0)
    zeros_test_vec[i] <- sum(df_title[,i] == 0 | df_title[,i] == "0")
  }

  zero_count_df <- cbind.data.frame(cols_vec, as.numeric(zeros_count_vec))
  names(zero_count_df) <- c("column_name", "number_zeros")

  # Append df_title to the dataframe name
  assign(paste0("zero_count_df_", deparse(substitute(df_title))), zero_count_df,
         envir = .GlobalEnv)
}
```

```{r read data}
lax0_data <- read.csv("LAXdata0.csv") #reading in data
lax1_data <- read.csv("LAXdata1.csv") #reading in data
soc0_data <- read.csv("SOCdata0.csv") #reading in data
soc1_data <- read.csv("SOCdata1.csv") #reading in data
```


## <span style= "color:#0C2340" > DATA CLEANING <span style= "color:#0C2340" >
```{r cleaning df names & dropping vars missing 95%}
cutoff_val <- .95
####################### LAX 0 ####################### 
lax0_data <- clean_names(lax0_data) #cleaning names to snakecase
#dim(lax0_data) #check dimensions
#create a cutoff to use for dropping a column if more than that percent are zero
drop_var_cutoff_lax0 <- dim(lax0_data)[1]*cutoff_val

####################### LAX 1 #######################
lax1_data <- clean_names(lax1_data)  #cleaning names to snakecase
#dim(lax1_data) #check dimensions
drop_var_cutoff_lax1 <- dim(lax1_data)[1]*cutoff_val #lax 1 drop cutoff

####################### SOC 0 #######################
soc0_data <- clean_names(soc0_data) #cleaning names to snakecase
#dim(soc0_data) #check dimensions
drop_var_cutoff_soc0 <- dim(soc0_data)[1]*cutoff_val #soc 0 drop cutoff

####################### SOC 1 #######################
soc1_data <- clean_names(soc1_data) #cleaning names to snakecase
#dim(soc1_data) #check dimensions
drop_var_cutoff_soc1 <- dim(soc1_data)[1]*cutoff_val #soc 0 drop cutoff
```


```{r dropping cols missing more than cutoff - lax0}
cols_to_remove_vec <- c("month_name", "day_name", "x",
                        "team_name", "total_activities", "athlete_weight", 
                        "player_name", "jersey")

####################### LAX 0 #######################
calc_num_zeros_by_col(lax0_data)
#zero_count_df_lax0_data
miss_over_cutoff_perc_df_lax0_data <- zero_count_df_lax0_data %>% 
  filter(number_zeros >= drop_var_cutoff_lax0)
lax0_data <- lax0_data %>%
  select(-one_of(miss_over_cutoff_perc_df_lax0_data$column_name)) %>%
  select(!all_of(cols_to_remove_vec)) %>%
  select(-contains("heart")) 

# changing position name to a numeric factor
lax0_data$position_name <- as.numeric(revalue(lax0_data$position_name, 
        c("Attack"=1, "D-Mid"=2, "Defense"=3, 
          "FOS"=4, "LSM"=5, "Midfield"=6)))

# adding a column for a "unique session" --> player, date, start time
lax0_data$unique_session <- paste(lax0_data$name_id, 
                                  lax0_data$date, 
                                  lax0_data$unix_start_time, 
                                  sep="-")
```

```{r dropping cols missing more than cutoff - lax1}
####################### LAX 1 #######################
calc_num_zeros_by_col(lax1_data)
#zero_count_df_lax1_data
miss_over_cutoff_perc_df_lax1_data <- zero_count_df_lax1_data %>%
  filter(number_zeros >= drop_var_cutoff_lax1)
lax1_data <- lax1_data %>%
  select(-one_of(miss_over_cutoff_perc_df_lax1_data$column_name)) %>%
  select(-contains(cols_to_remove_vec))

# changing position name to a numeric factor
pos_options <- unique(lax1_data$position_name)
lax1_data$position_name <- as.numeric(revalue(lax1_data$position_name, 
        c("Midfielder"=1, "Midfielder - Attacking"=2, "Attacker"=3, 
          "Defender"=4, "Midfielder - Defensive"=5)))

# adding a column for a "unique session" --> player, date, start time
lax1_data$unique_session <- paste(lax1_data$name_id, 
                                  lax1_data$date, 
                                  lax1_data$start_time, 
                                  sep="-")
```

```{r dropping cols missing more than cutoff - Soc0}
####################### SOC 0 #######################
calc_num_zeros_by_col(soc0_data)
#zero_count_df_soc1_data
miss_over_cutoff_perc_df_soc0_data <- zero_count_df_soc0_data %>%
  filter(number_zeros >= drop_var_cutoff_soc0)
soc0_data <- soc0_data %>%
  select(-one_of(miss_over_cutoff_perc_df_soc0_data$column_name)) %>%
  select(-contains(cols_to_remove_vec))

# changing position name to a numeric factor
pos_options <- unique(soc0_data$position_name)
soc0_data$position_name <- as.numeric(revalue(soc0_data$position_name, 
        c("Center Back"=4,
          "Center Mid"=2,
          "Forward"=1,
          "Outside Mid"=6, 
          "Outside Back"=5,
          "GoalKeeper"=0, 
          "6/8"=3,#midfield
          "2/3"=5,#outside back
          "7/11"=1,  #outside forward
          "9"  =1, #striker
          "1" = 0, #GK 
          "4/5" =4,
          "Goalkeeper"=0, 
          "Defensive Line"=4, 
          "Defensive Back"   =4,
          "Central Midfielder"=3, 
          "Defender"=4,
          "Missing Position"=7, 
          "Fullback"=5, 
          "Central Defender"=4, 
          "Winger"=6)))

# adding a column for a "unique session" --> player, date, start time
soc0_data$unique_session <- paste(soc0_data$name_id, 
                                  soc0_data$date, 
                                  soc0_data$start_time, 
                                  sep="-")
```

```{r dropping cols missing more than cutoff - Soc1}
####################### SOC 1 #######################
calc_num_zeros_by_col(soc1_data)
#zero_count_df_soc1_data
miss_over_cutoff_perc_df_soc1_data <- zero_count_df_soc1_data %>%
  filter(number_zeros >= drop_var_cutoff_soc1)
soc1_data <- soc1_data %>%
  select(-one_of(miss_over_cutoff_perc_df_soc1_data$column_name)) %>%
  select(-contains(cols_to_remove_vec)) %>%
  select(-contains(c("average_high_speed_distance",
  "high_speed_running_distance")))


# FORWARD 1, MIDFIELD 2, BACK 3, Utility 4, WINGER 5, GK 0
soc1_data$position_name <- as.numeric(revalue(soc1_data$position_name, 
        c("Forward"=1, "Midfield"=2, "Center Back" = 3,
          "Striker"=1, "Keeper" = 0, "Outside Back" = 4,
          "Center Midfield"=2, "Defender"=3, "Midfielder" = 2, 
          "Goal Keeper"=0, "Defensive Midfielder"=2, "Central Midfielder"=2,
          "Attacking Midfielder"=2, "Centre Back"=3, "Utility"=4, 
          "Wing"=5, "Back"=3, "Wide"=5)))

# adding a column for a "unique session" --> player, date, start time
soc1_data$unique_session <- paste(soc1_data$name_id, 
                                  soc1_data$date, 
                                  soc1_data$start_time, 
                                  sep="-")
```


```{r indoor outdoor dataframes}
lax0_data$location <- as.factor(ifelse(lax0_data$total_distance == 0,
                                       "indoor", "outdoor"))
lax1_data$location <- as.factor(ifelse(lax1_data$total_distance == 0,
                                       "indoor", "outdoor"))
soc0_data$location <- as.factor(ifelse(soc0_data$total_distance == 0,
                                       "indoor", "outdoor"))
soc1_data$location <- as.factor(ifelse(soc1_data$total_distance == 0,
                                       "indoor", "outdoor"))

#lax0_data %>% select("date", "location", "total_distance", "total_player_load")

# #confirming logic for filling rows on a subset of data
# set.seed(123)
# sample_rows <- sample(dim(lax0_data)[1], size=500)
# in_out_sub <- lax0_data %>% 
#   select(c("date", "total_distance", "total_player_load")) 
# in_out_sub <- in_out_sub[sample_rows, ]
# in_out_sub$location <- ifelse(in_out_sub$total_distance == 0, "indoor", "outdoor")

not_include_indoor_vec <- c("duration", "distance", "meta", "total_effort", 
                            "heart_rate", "hr", "velocity", "acceleration",
                            "deceleration", "metre", "meterage",
                            "exertion_index","max_vel_max", 
                            "footstrikes", "running_series_count", 
                            "running_imbalance")

lax0_indoor_full_df <- lax0_data %>%
  filter(location=="indoor") %>%
  select(-contains(not_include_indoor_vec))

lax1_indoor_full_df <- lax1_data %>%
  filter(location=="indoor") %>%
  select(-contains(not_include_indoor_vec))

soc0_indoor_full_df <- soc0_data %>%
  filter(location=="indoor") %>%
  select(-contains(not_include_indoor_vec))

soc1_indoor_full_df <- soc1_data %>%
  filter(location=="indoor") %>%
  select(-contains(not_include_indoor_vec))
```



```{r cleaning duration to numeric}
# testing_names_vec <- lax0_data %>% select_if(is.character) %>%
#   select(contains(c("time", "duration"))) %>% names()
  
# for (i in seq_along(testing_names_vec)) {
#   col_name <- testing_names_vec[i]
#   
#   lax0_data[[col_name]] <- chron(times = lax0_data[[col_name]])
#   lax0_data[[col_name]] <- hms(lax0_data[[col_name]])
#   lax0_data[[col_name]] <- hour(lax0_data[[col_name]])*60 +
#     minute(lax0_data[[col_name]])
# }


#################################### LAx 0 #############################
dur_chr_df <- lax0_data %>% 
  select(contains(c("duration", "time")))%>% 
  select_if(is.character)

for (q in seq_along(names(dur_chr_df))){
  col_vec <- dur_chr_df[, q]
  col_name <- names(dur_chr_df[q])

  col_vec <- str_replace_all(col_vec, pattern="[[:punct:]]", replacement = "")
  
  for (r in 1:length(col_vec)){
   hrs_val <- as.numeric(substr(col_vec[r], 1, 2))
   min_val <- as.numeric(substr(col_vec[r], 3, 4))
   tot_min <- as.numeric((hrs_val*60) + min_val) 
   col_vec[r] <- tot_min
  }
  
  dur_chr_df[, q] <- as.numeric(col_vec)
  lax0_data[[col_name]] <- dur_chr_df[, q]
}




#################################### LAX 1 #############################
dur_chr_df <- lax1_data %>%
  select(contains(c("duration", "time")))%>%
  select_if(is.character)

for (q in seq_along(names(dur_chr_df))){
  col_vec <- dur_chr_df[, q]
  col_name <- names(dur_chr_df[q])

  col_vec <- str_replace_all(col_vec, pattern="[[:punct:]]", replacement = "")

  for (r in 1:length(col_vec)){
   hrs_val <- as.numeric(substr(col_vec[r], 1, 2))
   min_val <- as.numeric(substr(col_vec[r], 3, 4))
   tot_min <- as.numeric((hrs_val*60) + min_val)
   col_vec[r] <- tot_min
  }

  dur_chr_df[, q] <- as.numeric(col_vec)
  lax1_data[[col_name]] <- dur_chr_df[, q]
}






#################################### SOC 0 #############################
dur_chr_df <- soc0_data %>%
  select(contains(c("duration", "time"))) %>%
  select_if(is.character)

for (q in seq_along(names(dur_chr_df))){
  col_vec <- dur_chr_df[, q]
  col_name <- names(dur_chr_df[q])

  col_vec <- str_replace_all(col_vec, pattern="[[:punct:]]", replacement = "")

  for (r in 1:length(col_vec)){
   hrs_val <- as.numeric(substr(col_vec[r], 1, 2))
   min_val <- as.numeric(substr(col_vec[r], 3, 4))
   tot_min <- as.numeric((hrs_val*60) + min_val)
   col_vec[r] <- tot_min
  }

  dur_chr_df[, q] <- as.numeric(col_vec)
  soc0_data[[col_name]] <- dur_chr_df[, q]
}




#################################### SOC 1 #############################
dur_chr_df <- soc1_data %>%
  select(contains(c("duration", "time")))%>%
  select_if(is.character)

for (q in seq_along(names(dur_chr_df))){
  col_vec <- dur_chr_df[, q]
  col_name <- names(dur_chr_df[q])

  col_vec <- str_replace_all(col_vec, pattern="[[:punct:]]", replacement = "")

  for (r in 1:length(col_vec)){
   hrs_val <- as.numeric(substr(col_vec[r], 1, 2))
   min_val <- as.numeric(substr(col_vec[r], 3, 4))
   tot_min <- as.numeric((hrs_val*60) + min_val)
   col_vec[r] <- tot_min
  }

  dur_chr_df[, q] <- as.numeric(col_vec)
  soc1_data[[col_name]] <- dur_chr_df[, q]
}
```


### <span style= "color:#0C2340" > ADDING GAME/TRAINING COLUMN <span style= "color:#0C2340" >

```{r source scraping game data file}
#source("scraping_sport_schedules.r")
lax0_game_dates <- read.csv(".//Exported_CSVs//lax0_game_dates.csv")$x
lax1_game_dates <- read.csv(".//Exported_CSVs//lax1_game_dates.csv")$x
soc0_game_dates <- read.csv(".//Exported_CSVs//soc0_game_dates.csv")$x
soc1_game_dates <- read.csv(".//Exported_CSVs//soc1_game_dates.csv")$x
```


```{r creating activity_type column}

####################### LAX 0 #######################
lax0_data$activity_type <- as.factor(ifelse(lax0_data$date %in% lax0_game_dates, 
                                  "game", "training"))
lax0_data$activity_type_binary <- as.numeric(ifelse(lax0_data$date %in% lax0_game_dates, 
                                  1, 0))

####################### LAX 1 #######################
lax1_data$activity_type <- as.factor(ifelse(lax1_data$date %in% lax1_game_dates, 
                                  "game", "training"))
lax1_data$activity_type_binary <- as.numeric(ifelse(lax1_data$date %in% lax1_game_dates, 
                                  1, 0))

####################### SOC 0 #######################
soc0_data$activity_type <- as.factor(ifelse(soc0_data$date %in% soc0_game_dates, 
                                  "game", "training"))
soc0_data$activity_type_binary <- as.numeric(ifelse(soc0_data$date %in% soc0_game_dates, 
                                  1, 0))

####################### SOC 1 #######################
soc1_data$activity_type <- as.factor(ifelse(soc1_data$date %in% soc1_game_dates, 
                                  "game", "training"))
soc1_data$activity_type_binary <- as.numeric(ifelse(soc1_data$date %in% soc1_game_dates, 
                                  1, 0))
```

```{r write cleaned data to csv}
# write.csv(lax0_data,".\\lax0_data_cleaned.csv",row.names=FALSE)
# 
# write.csv(lax1_data,".\\lax1_data_cleaned.csv",row.names=FALSE)
# 
# write.csv(soc0_data,".\\soc0_data_cleaned.csv",row.names=FALSE)
# 
# write.csv(soc1_data,".\\soc1_data_cleaned.csv",row.names=FALSE)

#loading in data to confirm
# cleaned_data_lax0 <- read.csv(".\\Exported_CSVs\\lax0_data_cleaned.csv") 
```




